### ISSUE TITLE
For complete Ruby newbies - some tips

### ISSUE THREAD

**Issue by rmyadsk** [carlosonunez/tesla-oauth2-token-bot#1]
For newcomers (such as myself) who might be using Ruby for the first time, you can install Ruby on, say, a Ubuntu box with:

> apt install ruby-full
> ruby --version

You'll also need to install bundler:

> gem install bundle

Then you may proceed with the rest of the setup.

**Comment by carlosonunez** [comment]
Great suggestion! Feel free to open a pull request with these modifications. I’ll gladly merge them in thereafter!

**Comment by rmyadsk** [comment]
Okay, thanks. I'm newish to Github too so this will be my first pull request. Standby...

**Comment by carlosonunez** [comment]
Awesome!! Let me know if you need any help.

**Comment by rmyadsk** [comment]
And I'm right there. I want to hack up Readme.md, but it wants me to alter generate_token.rb.

**Comment by carlosonunez** [comment]
Can you elaborate? You should be able to modify the README without needing to touch the Ruby file.

**Comment by rmyadsk** [comment]
1. Click "New pull request" on https://github.com/carlosonunez/tesla-oauth2-token-bot/pulls
2. Click "master" - sends to generate_token.rb.

I now notice I can go to "Wiki" and attempt to edit with the message

> You’re making changes in a project you don’t have write access to. We’ve created a fork of this project for you to commit your proposed changes to. Submitting a change will write it to a new branch in your fork, so you can send a pull request.

So I'll try that now...
